[phases.setup]
nixPkgs = ['python310', 'ffmpeg']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = []

[start]
cmd = 'gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 300'
