[phases.setup]
nixPkgs = ['python311', 'ffmpeg']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'python -m pip install -r requirements.txt']

[start]
cmd = 'gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 600 --keepalive 5'
